name : Push_to_EC2

on:Push

jobs:
  deploy:
    name:Push to EC2 Instance
    runs-on:ubuntu_latest
    
    steps:
       - name:Checkout the code
       uses:actions/checkout@v3
    
       - name:Deploy to my Ec2 innstance
       uses:easingthemes/ssh-deploy@v2.1.5
    
    env:
    SSH_PRIVATE_KEY:${{ secrets.EC2_SSH_KEY }}
    source: "./"
    REMOTE_HOST:${{secrets.REMOTE_HOST}}
    REMOTE_USER:${{secrets.REMOTE_USER}}
    TARGET:"/home/ec2-user/"
    
    - name:Install Dependencies
    run: pip3 install -r requirements.txt
    
    
    
    

